export const cleanText = (str) => {
  if (!str || typeof str !== 'string') return str;
  return str
    .replace(/100%\s*Pure\s*&\s*Natural/gi, 'Pure & Natural')
    .replace(/100%\s*Pure\s*Natural/gi, 'Pure & Natural')
    .replace(/100%\s*Pure/gi, 'Pure')
    .replace(/100%\s*Natural/gi, 'Pure Natural')
    .replace(/100%\s*Organic/gi, 'Pure Organic')
    .replace(/100%\s*Chemical\s*Free/gi, 'Chemical Free')
    .replace(/100%\s*Fresh/gi, 'Fresh')
    .replace(/100%\s*Quality/gi, 'Quality')
    .replace(/100%\s*Heirloom/gi, 'Heirloom')
    .replace(/100%\s*bananas\b/gi, 'pure bananas')
    .replace(/100%\s*banana\b/gi, 'pure banana')
    .replace(/100%\s*moringa\b/gi, 'pure moringa')
    .replace(/100%\s*amla\b/gi, 'pure amla')
    .replace(/100%\s*wheatgrass\b/gi, 'pure wheatgrass')
    .replace(/100%\s*sprouted\s*ragi\b/gi, 'pure sprouted ragi')
    .replace(/100%\s*coriander\b/gi, 'pure coriander')
    .replace(/100%\s*curry\b/gi, 'pure curry')
    .replace(/100%\s*mint\b/gi, 'pure mint')
    .replace(/100%\s*spinach\b/gi, 'pure spinach')
    .replace(/100%\s*beetroot\b/gi, 'pure beetroot')
    .replace(/100%\s*carrot\b/gi, 'pure carrot')
    .replace(/100%\s*/gi, 'Pure ')
    .replace(/\b100%\b/g, 'Pure')
    .replace(/Pure\s+Pure/gi, 'Pure')
    .replace(/<strong>\s*/gi, '<strong>')
    .replace(/\s*<\/strong>/gi, '</strong>');
};
